language: android

jdk: oraclejdk8

env:
  global:
    - ANDROID_TARGET=android-26
    - ANDROID_ABI=armeabi-v7a

before_install:
 - chmod +x gradlew
 - mkdir "$ANDROID_HOME/licenses" || true
 - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
 - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
 - echo -e "\nd975f751698a77b662f1254ddbeed3901e976f5a" > "$ANDROID_HOME/licenses/intel-android-extra-license"
android:
 components:
  - tools
  - platform-tools
  - build-tools-26.0.0
  - tools
  - android-26
  - extra-android-m2repository
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

script:
  - ./gradlew build jacocoTestReport assembleAndroidTest
  - ./gradlew codeCoverageReport
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
  
# Specify at least one system image,
# if you need to run emulator(s) during your tests
#- sys-img-armeabi-v7a-android-22
#- sys-img-armeabi-v7a-android-17

